HELP_MESSAGE = 'Usage: @TCurrencyBot 13USD [EUR, UAH, ...]'
BAD_FORMAT = 'Incorrect format.'
BAD_CURRENCY_MESSAGE = '{currency} is an incorrect currency.\nSee {api_provider_url} for the list of supported currencies.'
BAD_AMOUNT_MESSAGE = 'Incorrect amount of currency. It must be higher than {minimal_amount} or empty (will be handled as 1).'
DEFAULT_CURRENCY_MESSAGE = '{default_currency} is default base currency. Please, consider to choose another currency to convert'
