RESULT_MESSAGE = '{amount} {cur1} = {result} {cur2}'
USAGE_MESSAGE = '```Usage: /c arg1 [arg2]```'
EXAMPLE_MESSAGE = '```Example: /c 15USD EUR```'
BAD_FORMAT = 'Incorrect format. See /help and /example and try again.'
BAD_CURRENCY_MESSAGE = 'Incorrect currency. See /support for the list of supported currencies.'
BAD_AMOUNT_MESSAGE = 'Incorrect amount of currency. It must be higher than 0.01 or empty (will be handled as 1).'
